### ISSUE TITLE
route overview (main.ipynb)

### ISSUE THREAD

**Issue by kostubhagarwal** [uw-midsun/strategy_msxvi#35]
You should be able to setup route_model table in a postgresql database by running route_model.py (you will have to create database manually tho). Then using functions in db_fetch.py you should be able to load data to memory. Then simply refactor the code to reproduce the following three graphs. 

Distance (Stage)
Elevation Profile (Stage)
Elevation Profile (Total)

**Comment by raiyanjaz** [comment]
When refactoring the code to reproduce the graphs, I noticed that the query Elevation Profile (stage) uses is:
```
query = f"""
SELECT * 
FROM route_model_df
WHERE stage_name LIKE '{STAGE_SYMBOL}_%'
ORDER BY id 
"""
```
However, in our case we do not have a column called id in our database. I was wondering if it is possible to know what the column id stored previously

**Comment by kostubhagarwal** [comment]
i think it was the first column. but don't use those queries (the old code converts sequel queries into python - which is dumb).  pull the values straight from route_model_df.

```
from db_fetch import load_data_to_memory
route_model_df, irradiance_df = load_data_to_memory()
```

**Comment by raiyanjaz** [comment]
Okay, and for the graphs is there anything I can compare it to? Should it look similar to the output of the previous code?

**Comment by kostubhagarwal** [comment]
It should look similar to the output of the previous code. Totally your call though!

On Oct 22, 2024, at 2:28 PM, Raiyan Aaijaz ***@***.***> wrote:

﻿

Okay, and for the graphs is there anything I can compare it to? Should it look similar to the output of the previous code?

**Comment by raiyanjaz** [comment]
Planning on completing the issue by 10/27/2024
